### ISSUE TITLE
depth noise model

### ISSUE THREAD

**Issue by seann999** [ToyotaResearchInstitute/simnet#1]
I was looking through the code and was curious about the depth noise model.
I found this:
https://github.com/ToyotaResearchInstitute/simnet/blob/main/simnet/lib/camera.py
but I can't seem to find `camera_noise`. Is it in the repository?

**Comment by kevinleestone** [comment]
We haven't published the simulator at this time (which includes the camera noise models for RGB and Depth modalities). We hope to open source it in a future work, but for now this may be a helpful starting point:
 * For RGB we implemented the pipeline from [Unprocessing Images for Learned Raw Denoising](https://arxiv.org/abs/1811.11127).
 * For Depth we implemented a fairly standard RGB-D noise pipeline. You can refer to [A Benchmark for RGB-D Visual Odometry, 3D Reconstruction and SLAM](https://www.doc.ic.ac.uk/~ahanda/VaFRIC/icra2014.pdf) for inspiration.
